import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    width: 375,
    height: 812,
    position: 'relative',
    backgroundColor: 'white',
    overflow: 'hidden',
  },
  backgroundShape1: {
    width: 373.53,
    height: 442.65,
    left: 148.04,
    top: 261.57,
    position: 'absolute',
    transform: [{ rotate: '-110deg' }],
    backgroundColor: '#D9E4FF',
  },
  backgroundShape2: {
    width: 402.87,
    height: 442.65,
    left: 576.17,
    top: -257.71,
    position: 'absolute',
    transform: [{ rotate: '92deg' }],
    backgroundColor: '#323660',
  },
  backgroundShape3: {
    width: 166,
    height: 52,
    left: 105,
    top: 417,
    position: 'absolute',
    backgroundColor: '#F1F1F1',
    borderRadius: 59.12,
    justifyContent: 'flex-start',
    alignItems: 'center',
    display: 'flex',
    paddingLeft: 19.71,
    paddingRight: 19.71,
    paddingTop: 15.76,
    paddingBottom: 15.76,
  },
  title: {
    left: 97,
    top: 266,
    position: 'absolute',
    textAlign: 'center',
    color: '#202020',
    fontSize: 21,
    fontFamily: 'Raleway',
    fontWeight: '700',
    lineHeight: 30,
  },
  subtitle: {
    width: 290,
    height: 57,
    left: 43,
    top: 301,
    position: 'absolute',
    textAlign: 'center',
    color: 'black',
    fontSize: 19,
    fontFamily: 'Nunito Sans',
    fontWeight: '300',
    lineHeight: 27,
  },
  email: {
    left: 50,
    top: 371,
    position: 'absolute',
    textAlign: 'center',
    color: 'black',
    fontSize: 16,
    fontFamily: 'Nunito Sans',
    fontWeight: '700',
    lineHeight: 25,
    letterSpacing: 1.6,
  },
  input: {
    width: 200,
    height: 40,
    left: 87,
    top: 420,
    position: 'absolute',
    backgroundColor: '#F1F1F1',
    borderRadius: 10,
    paddingLeft: 10,
    fontSize: 16,
  },
  verifyButton: {
    width: 201,
    height: 50,
    left: 87,
    top: 500,
    position: 'absolute',
    backgroundColor: '#323660',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  verifyButtonText: {
    color: '#F3F3F3',
    fontSize: 22,
    fontFamily: 'Nunito Sans',
    fontWeight: '300',
  },
  resendText: {
    left: 152,
    top: 606,
    position: 'absolute',
    textAlign: 'center',
    color: '#4472C4',
    fontSize: 15,
    fontFamily: 'Nunito Sans',
    fontWeight: '900',
  },
  logoutText: {
    left: 168,
    top: 718,
    position: 'absolute',
    opacity: 0.9,
    textAlign: 'center',
    color: '#202020',
    fontSize: 15,
    fontFamily: 'Nunito Sans',
    fontWeight: '300',
  },
});

export default styles;
