import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    padding: 20,
    position: 'relative',
    paddingBottom:30
  },
  backgroundShapes: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: -1,
  },
  shape1: {
    width: 137.56,
    height: 151.14,
    position: 'absolute',
    top: 206.03,
    left: 384.67,
    backgroundColor: '#323660',
    transform: [{ rotate: '-156deg' }],
  },
  shape2: {
    width: 272.07,
    height: 361.19,
    position: 'absolute',
    top: 231.04,
    left: 212.68,
    backgroundColor: '#D9E4FF',
    transform: [{ rotate: '-162deg' }],
  },
  shape3: {
    width: 332,
    height: 390,
    position: 'absolute',
    top: 174.13,
    left: 208.64,
    backgroundColor: '#323660',
    transform: [{ rotate: '-177deg' }],
  },
  title: {
    fontSize: 48,
    fontWeight: '700',
    color: '#202020',
    fontFamily: 'Raleway',
    marginTop: 200,
    marginLeft: 20,
  },
  subtitle: {
    fontSize: 19,
    fontWeight: '300',
    color: '#202020',
    fontFamily: 'Nunito Sans',
    marginLeft: 20,
    marginTop: 10,
  },
  input: {
    backgroundColor: '#F1F1F1',
    borderRadius: 59.12,
    height: 52,
    marginTop: 30,
    paddingLeft: 20,
    paddingRight: 20,
    fontSize: 15,
    fontFamily: 'Poppins',
  },
  forgotPassword: {
    alignSelf: 'flex-start',
    marginTop: 10,
  },
  forgotPasswordText: {
    color: '#323660',
    fontSize: 15,
    fontFamily: 'Nunito Sans',
    fontWeight: '600',
  },
  loginButton: {
    backgroundColor: '#323660',
    borderRadius: 16,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
  },
  loginButtonText: {
    color: '#F3F3F3',
    fontSize: 22,
    fontFamily: 'Nunito Sans',
    fontWeight: '300',
  },
  googleButton: {
    backgroundColor: '#FFEBEB',
    borderRadius: 16,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  googleButtonText: {
    color: '#707070',
    fontSize: 15,
    fontFamily: 'Nunito Sans',
    fontWeight: '500',
  },
  facebookButton: {
    backgroundColor: '#E5EBFC',
    borderRadius: 16,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  facebookButtonText: {
    color: '#707070',
    fontSize: 15,
    fontFamily: 'Nunito Sans',
    fontWeight: '500',
  },
  signupContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  signupText: {
    color: '#202020',
    fontSize: 15,
    fontFamily: 'Nunito Sans',
    fontWeight: '300',
  },
  signupLink: {
    color: '#4472C4',
    fontSize: 15,
    fontFamily: 'Nunito Sans',
    fontWeight: '900',
    textDecorationLine: 'underline',
  },
});

export default styles;
