import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    padding: 20,
    position: 'relative',
  },
  backgroundShapes: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: -1,
  },
  shape1: {
    width: 659.33,
    height: 513.44,
    position: 'absolute',
    top: -183,
    left: -118,
  },
  shape2: {
    width: 311.01,
    height: 367.30,
    position: 'absolute',
    top: 340.55,
    left: 425.96,
    backgroundColor: '#F2F5FE',
    transform: [{ rotate: '158deg' }],
  },
  image: {
    width: 293,
    height: 293,
    position: 'absolute',
    top: 50,
    left: 50,
  },
  title: {
    fontSize: 36,
    fontWeight: '700',
    color: '#202020',
    fontFamily: 'Raleway',
    textAlign: 'center',
    marginTop: 317,
  },
  inputContainer: {
    width: 335,
    marginTop: 30,
    marginLeft: 20,
    gap: 7.91,
  },
  input: {
    backgroundColor: '#F1F1F1',
    borderRadius: 59.29,
    height: 52.37,
    paddingLeft: 20,
    paddingRight: 20,
    fontSize: 15,
    fontFamily: 'Poppins',
    marginBottom: 10,
  },
  phoneInput: {
    backgroundColor: '#F1F1F1',
    borderRadius: 59.29,
    height: 55.34,
    paddingLeft: 20,
    paddingRight: 20,
    fontSize: 15,
    fontFamily: 'Poppins',
    marginBottom: 10,
  },
  signupButton: {
    backgroundColor: '#323660',
    borderRadius: 16,
    height: 61,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
  },
  signupButtonText: {
    color: '#F3F3F3',
    fontSize: 22,
    fontFamily: 'Nunito Sans',
    fontWeight: '300',
  },
  loginLink: {
    position: 'absolute',
    color: '#202020',
    fontSize: 15,
    fontFamily: 'Nunito Sans',
    fontWeight: '300',
    textAlign: 'center',
    bottom: -30,
    left: 110,
  },
  loginLinkText: {
    color: '#4472C4',
    fontSize: 15,
    fontFamily: 'Nunito Sans',
    fontWeight: '900',
    textDecorationLine: 'underline',
  },
});

export default styles;
